###################### Filebeat Configuration Example #########################

filebeat.inputs:

- type: filestream
  enabled: false
  paths:
    - /var/log/*.log

# ============================== Filebeat modules ==============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1

# =================================== Kibana ===================================

setup.kibana:
  host: "192.168.1.50:8080"

# ---------------------------- Elasticsearch Output ----------------------------
# output.elasticsearch:
#   hosts: ["192.168.1.50:9200"]

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  hosts: ["192.168.1.50:5044"]

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~