#################### Packetbeat Configuration Example #########################

packetbeat.interfaces.device: any

packetbeat.interfaces.internal_networks:
  - private

# =================================== Flows ====================================

packetbeat.flows:
  timeout: 30s
  period: 10s

# =========================== Transaction protocols ============================

packetbeat.protocols:
- type: icmp
  enabled: true

- type: amqp
  ports: [5672]

- type: cassandra
  ports: [9042]

- type: dhcpv4
  ports: [67, 68]

- type: dns
  ports: [53]

- type: http
  ports: [80, 8080, 8000, 5000, 8002]

- type: memcache
  ports: [11211]

- type: mysql
  ports: [3306,3307]

- type: pgsql
  ports: [5432]

- type: redis
  ports: [6379]

- type: thrift
  ports: [9090]

- type: mongodb
  ports: [27017]

- type: nfs
  ports: [2049]

- type: tls
  ports:
    - 443   # HTTPS
    - 993   # IMAPS
    - 995   # POP3S
    - 5223  # XMPP over SSL
    - 8443
    - 8883  # Secure MQTT
    - 9243  # Elasticsearch

- type: sip
  ports: [5060]

# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
  host: "192.168.1.50:8080"

# ================================== Outputs ===================================

# ---------------------------- Elasticsearch Output ----------------------------
# output.elasticsearch:
#   hosts: ["192.168.1.50:9200"]

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  hosts: ["192.168.1.50:5044"]