- name: Provision metricbeat and filebeat
  hosts: all
  vars:
    ansible_python_interpreter: auto
  pre_tasks:
    - name: Reboot host and wait restart to avoid DPKG lock bug
      become: true
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 10
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: whoami
  tasks:
    - name: Add Elasticsearch Apt key
      become: true
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
    - name: Add Elasticsearch repository.
      become: true
      apt_repository:
        repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
        state: present
    - name: Install packages
      become: true
      apt: 
        name: 
          - elasticsearch
          - kibana
          - logstash
        state: present
        update_cache: yes
    - name: Change Elasticsearch discovery type to 'single-node'
      become: true
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        line: "discovery.type: single-node"
    - name: Change Elasticsearch network host to '0.0.0.0'
      become: true
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        line: "network.host: 0.0.0.0"
    - name: Copy input beats logstash
      become: true
      copy:
        src: ./configs/beats-input.conf
        dest: /etc/logstash/conf.d/02-beats-input.conf
    - name: Copy output elasticsearch logstash
      become: true
      copy:
        src: ./configs/elasticsearch-output.conf
        dest: /etc/logstash/conf.d/30-elasticsearch-output.conf
    - name: Enable elasticsearch service
      become: true
      service:
        name: elasticsearch
        enabled: true
        state: started
    - name: Enable kibana service
      become: true
      service:
        name: kibana
        enabled: true
        state: started
    - name: Enable logstash service
      become: true
      service:
        name: logstash
        enabled: true
        state: started
## Nginx
    - name: Disable apache service if exist
      become: true
      service:
        name: apache2
        enabled: false
        state: stopped
      register: unused_disable
      failed_when: "unused_disable is failed and ('find' not in unused_disable.msg and 'found' not in unused_disable.msg)"
    - name: Install packages
      become: true
      apt: 
        name: 
          - nginx
        state: present
    - name: Delete default nginx configuration file
      become: true
      file:
        state: absent
        path: /etc/nginx/sites-available/default
    - name: Copy Nginx custom configuration as the default configuration
      become: true
      copy:
        src: ./configs/hello-nginx-conf
        dest: /etc/nginx/sites-available/default
    - name: Increase Nginx max body size
      become: true
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: 'http {'
        insertafter: '^http {'
        line: client_max_body_size 10M;
    - name: Validates new configuration
      become: true
      shell: 
        cmd: nginx -t
    - name: Reload nginx config
      become: true
      service:
        name: nginx
        enabled: true
        state: reloaded        