- name: Provision Node App
  hosts: default
  vars:
    ansible_python_interpreter: auto
  tasks:
    - name: Download node setup script
      get_url:
        url: https://deb.nodesource.com/setup_14.x
        dest: ~/nodesource_setup.sh
        mode: 0755
    - name: Execute node setup script
      become: true
      shell: /home/vagrant/nodesource_setup.sh
    - name: Install packages
      become: true
      apt: 
        name: 
          - nodejs
          - build-essential
        state: present
        update_cache: yes        
    - name: Creates server-example directory
      file:
        path: ~/server-example
        state: directory
    - name: Install pm2 package globally
      become: true
      shell: 
        cmd: npm install pm2@latest -g        
    - name: Install apollo-server package
      become: true
      shell: 
        cmd: npm install --prefix /home/vagrant/server-example/ apollo-server
    - name: Install graphql package
      become: true
      shell: 
        cmd: npm install --prefix /home/vagrant/server-example/ graphql
    - name: Copy JS app to app directory
      copy:
        src: ./index.js
        dest: ~/server-example/index.js
    - name: Kills PM2 processes
      shell: 
        cmd: pm2 kill
    - name: Starts PM2 on startup
      shell: 
        cmd: pm2 startup systemd | grep "sudo" | sh
    - name: Starts PM2 app
      become: true
      shell: 
        cmd: systemctl start pm2-vagrant
    - name: Starts JS app
      shell: 
        cmd: pm2 start ~/server-example/index.js
    - name: Saves PM2 state
      shell: 
        cmd: pm2 save