- name: Provision Node App
  hosts: all
  vars:
    ansible_python_interpreter: auto
  pre_tasks:
    - name: Reboot host and wait restart to avoid DPKG lock bug
      become: true
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 10
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: whoami
    - name: Add universe repository for bionic
      become: true
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu bionic universe
        state: present
      when: ansible_distribution_release == 'bionic'
  roles:
    - name: geerlingguy.nodejs
      become: true
  tasks:
    - name: Creates server-example directory
      file:
        path: ~/server-example
        state: directory
    - name: "Install PM2"
      become: true
      npm:
        global: yes
        name: pm2
    - name: "Install Apollo and GraphQL"
      npm:
        path: /home/ubuntu/server-example
        name: "{{ item }}"
      loop:
        - apollo-server
        - graphql
    - name: Copy JS app to app directory
      copy:
        src: ./index.js
        dest: /home/ubuntu/server-example/index.js
    - name: Kills PM2 processes
      shell: 
        cmd: pm2 kill
    - name: Starts PM2 on startup
      shell: 
        cmd: pm2 startup systemd | grep "sudo" | sh
    - name: Starts PM2 app
      become: true
      shell: 
        cmd: systemctl start pm2-ubuntu
    - name: Starts JS app
      shell: 
        cmd: pm2 start /home/ubuntu/server-example/index.js
    - name: Saves PM2 state
      shell: 
        cmd: pm2 save