Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "forwarded_port", guest: 9200, host: 9200 # Elastic
  config.vm.network "forwarded_port", guest: 9300, host: 9300 # Elastic
  config.vm.network "forwarded_port", guest: 8080, host: 8080 # Forward to Kibana

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "metrics-playbook.yaml"
  end
end
