- name: Provision Nginx
  hosts: default
  vars:
    ansible_python_interpreter: auto
  tasks:
    - name: Disable apache service if exist
      become: true
      service:
        name: apache2
        enabled: false
        state: stopped
      register: unused_disable
      failed_when: "unused_disable is failed and ('find' not in unused_disable.msg and 'found' not in unused_disable.msg)"
    - name: Install packages
      become: true
      apt: 
        name: 
          - nginx
        state: present
    - name: Delete default nginx configuration file
      become: true
      file:
        state: absent
        path: /etc/nginx/sites-available/default
    - name: Copy Nginx custom configuration as the default configuration
      become: true
      copy:
        src: ./hello-nginx-conf
        dest: /etc/nginx/sites-available/default
    - name: Validates new configuration
      become: true
      shell: 
        cmd: nginx -t
    - name: Reload nginx config
      become: true
      service:
        name: nginx
        enabled: true
        state: reloaded